language: r
cache: packages

r:
  - release

branches:
  only:
    - master
    - travis

sudo: false

addons:
  apt:
    packages:
      - libmagick++-dev
      - libmagick++
      - magickcore

r_binary_packages:
  - coda
  - testthat
  - R.rsp
  - abind
  - ape
  - FNN
  - fields
  - ggplot2
  - MASS
  - Matrix
  - MCMCpack
  - mvtnorm
  - nnet
  - pdist
  - pROC
  - magick
  - animation
  - phytools
  - statmod
  - SparseM
  - truncnorm
  
r_github_packages:
  - jarioksa/BayesLogit-1

warnings_are_errors: false

r_check_revdep: false
